---
- name: Restart newrelic-infra
  service:
    name: newrelic-infra
    state: restarted
  when: not ansible_check_mode

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: not ansible_check_mode
