---
- name: Reload Systemd Daemon
  systemd:
    daemon_reload: true
  when: not ansible_check_mode

- name: Restart Elasticsearch
  service:
    name: elasticsearch
    state: restarted
  notify: Check Elasticsearch Cluster Status
  when: not ansible_check_mode

- name: Check Elasticsearch Cluster Status
  uri:
    url: http://{{ hostvars[inventory_hostname].ansible_host }}:9200/_cluster/health
    method: GET
    headers:
      Content-Type: "application/json"
  register: cluster_health
  until: cluster_health.json.status == "green"
  retries: 360
  delay: 5
  when: elasticsearch.force_boot == false
