---

common:
  repositories:
    elasticsearch_v7:
      enabled: true

elasticsearch:
  force_boot: false

  cluster_name_prefix: elastic-v7
  cluster_name_suffix: XXX

newrelic:
  label:
    environment: production
    serviceType: elasticsearch
    clusterName: XXX-v7

filebeat:
  fields:
    labels.clusterName: XXX-v7
    labels.serviceType: elasticsearch
    labels.environment: production
