---
- name: "Managed sysctl Params"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
    sysctl_set: yes
    reload: yes
  with_items:
    - "{{ sysctl }}"
